version: "3.2"
services:
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
      - ~/.gradle:/root/.gradle
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - ./bin/test_backend.sh
