version: "3.2"
services:
  frontend:
    image: kkarczmarczyk/node-yarn
    volumes:
      - type: bind
        source: ./
        target: /workspace
    working_dir: /workspace/frontend
    ports:
      - "8081:8081"
    command: bash -c "yarn install && yarn test"
