version: "3.2"
services:
  postgres:
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
      - ~/.gradle:/root/.gradle
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
    network_mode: service:e2e
    depends_on:
      - postgres
    command:
      - ./bin/run_backend.sh
  frontend:
    image: kkarczmarczyk/node-yarn
    volumes:
      - type: bind
        source: ./
        target: /workspace
    network_mode: service:e2e
    depends_on:
      - postgres
      - backend
    command:
      - ./bin/run_frontend.sh
  e2e:
    build:
      context: ./
      dockerfile: e2e/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./e2e/bundle_cache:/usr/local/bundle
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    command:
      - ./bin/run_e2e.sh
